In [131]:
# !pip install pandas

In [132]:
import pandas as pd

In [133]:
df_bronze = pd.read_csv('history.csv')

In [134]:
df_bronze.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn',
       'CustomerFeedback', 'MonthlyIncome'],
      dtype='str')

In [135]:
df_bronze.info()

<class 'pandas.DataFrame'>
RangeIndex: 5634 entries, 0 to 5633
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        5634 non-null   str
 1   gender            5634 non-null   str
 2   SeniorCitizen     5634 non-null   int64
 3   Partner           5634 non-null   str
 4   Dependents        5634 non-null   str
 5   tenure            5634 non-null   str
 6   PhoneService      5634 non-null   str
 7   MultipleLines     5634 non-null   str
 8   InternetService   5634 non-null   str
 9   OnlineSecurity    5634 non-null   str
 10  OnlineBackup      5634 non-null   str
 11  DeviceProtection  5634 non-null   str
 12  TechSupport       5634 non-null   str
 13  StreamingTV       5634 non-null   str
 14  StreamingMovies   5634 non-null   str
 15  Contract          5634 non-null   str
 16  PaperlessBilling  5634 non-null   str
 17  PaymentMethod     5634 non-null   str
 18  MonthlyCharges    5634 non-null   float64
 19  TotalCharges      5356 non-null   float64
 20  Churn             5634 non-null   str
 21  CustomerFeedback  5634 non-null   str
 22  MonthlyIncome     5634 non-null   int64
dtypes: float64(2), int64(2), str(19)
memory usage: 4.0 MB

## **Dicionário de dados**

- Varíavel 
- Definição
- Tipagem

| Nº | Coluna             | Descrição                                                                                                              | Tipo de dado         |
| -: | ------------------ | ---------------------------------------------------------------------------------------------------------------------- | -------------------- |
|  0 | `customerID`       | Identificador único do cliente                                                                                         | String               |
|  1 | `gender`           | Gênero do cliente (`Male`, `Female`)                                                                                   | Categórico (2 tipos) |
|  2 | `SeniorCitizen`    | Indica se o cliente é idoso                                                                                            | Boolean              |
|  3 | `Partner`          | Indica se o cliente possui parceiro(a), marido ou esposa                                                               | Boolean              |
|  4 | `Dependents`       | Indica se o cliente possui dependentes, como filhos                                                                    | Boolean              |
|  5 | `tenure`           | Tempo de relacionamento do cliente em meses                                                                            | Int                  |
|  6 | `PhoneService`     | Indica se o cliente possui serviço de telefonia. Padronizar `No`, `no`, `Yes` e `yes`                                  | Boolean              |
|  7 | `MultipleLines`    | Indica se o cliente possui mais de uma linha. Transformar `No phone service` em `No`                                   | Boolean              |
|  8 | `InternetService`  | Tipo de serviço de internet (`DSL`, `No`, `Fiber optic`)                                                               | Categórico (3 tipos) |
|  9 | `OnlineSecurity`   | Indica se o cliente possui serviço de segurança online. Transformar `No internet service` em `No`                      | Boolean              |
| 10 | `OnlineBackup`     | Indica se o cliente possui serviço de backup online. Transformar `No internet service` em `No`                         | Boolean              |
| 11 | `DeviceProtection` | Indica se o cliente possui proteção de dispositivos. Transformar `No internet service` em `No`                         | Boolean              |
| 12 | `TechSupport`      | Indica se o cliente possui suporte técnico. Transformar `No internet service` em `No`                                  | Boolean              |
| 13 | `StreamingTV`      | Indica se o cliente possui serviço de streaming de TV                                                                  | Boolean              |
| 14 | `StreamingMovies`  | Indica se o cliente possui serviço de streaming de filmes                                                              | Boolean              |
| 15 | `Contract`         | Tipo de contrato (`One year`, `Month-to-month`, `Two year`)                                                            | Categórico (3 tipos) |
| 16 | `PaperlessBilling` | Indica se a fatura é digital                                                                                           | Boolean              |
| 17 | `PaymentMethod`    | Método de pagamento (`Electronic check`, `Mailed check`, `Bank transfer (automatic)`, `Credit card (automatic)`)       | Categórico (4 tipos) |
| 18 | `MonthlyCharges`   | Valor cobrado mensalmente pelo plano e pelos serviços contratados                                                      | Float                |
| 19 | `TotalCharges`     | Valor total cobrado durante o período de relacionamento, podendo variar devido a descontos, promoções e outros fatores | Float                |
| 20 | `Churn`            | Indica se o cliente cancelou a assinatura                                                                              | Boolean              |
| 21 | `CustomerFeedback` | Feedback do cliente sobre a assinatura, incluindo pontos positivos e negativos                                         | String               |
| 22 | `MonthlyIncome`    | Renda mensal do cliente                                                                                                | Float                |

In [136]:
df_bronze.shape

(5634, 23)

In [137]:
df_bronze.sample(10)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,CustomerFeedback,MonthlyIncome
3871,2254-DLXRI,Female,0,No,No,1,Yes,Yes,Fiber optic,No,...,No,No,Month-to-month,Yes,Mailed check,79.15,79.15,No,I have been using the fiber optic internet ser...,5860
3264,9648-BCHKM,Female,0,Yes,Yes,18,Yes,Yes,No,No internet service,...,No internet service,No internet service,Two year,Yes,Credit card (automatic),24.65,471.35,No,I have been a customer with this company for 1...,4387
3898,9722-UJOJR,Male,0,Yes,Yes,29,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,70.75,1974.80,Yes,I have been a customer with this company for a...,8119
84,6686-YPGHK,Male,1,No,No,47,Yes,No,Fiber optic,Yes,...,No,Yes,Month-to-month,No,Mailed check,85.50,4042.30,Yes,I have been a customer with this company for 4...,1011
3256,9281-PKKZE,Female,0,Yes,No,46,No,No phone service,DSL,No,...,Yes,Yes,Month-to-month,Yes,Electronic check,43.95,2007.85,No,I have been a customer with this company for a...,7728
5552,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,No,Two year,No,Mailed check,73.35,NaN,No,I recently signed up for a two-year contract f...,8056
4505,2277-BKJKN,Female,1,Yes,No,71,Yes,No,Fiber optic,No,...,Yes,Yes,Two year,Yes,Electronic check,99.20,7213.75,No,I have been a loyal customer of this company f...,4175
2712,9796-MVYXX,Female,1,No,No,14,No,No phone service,DSL,Yes,...,No,No,Two year,No,Mailed check,39.70,692.35,No,I have been a customer with this DSL internet ...,661
2843,9625-QNLUX,Male,0,Yes,Yes,68,Yes,No,Fiber optic,Yes,...,Yes,Yes,Two year,Yes,Credit card (automatic),103.25,7074.40,No,I have been a loyal customer of this company f...,1800
5255,7674-YTAFD,Female,0,No,No,33,Yes,No,Fiber optic,No,...,No,No,One year,Yes,Bank transfer (automatic),79.95,2684.85,No,I have been a loyal customer of this fiber opt...,8496

### Verificação das colunas em geral: quantos valores únicos, nulos e duplicados

In [138]:
for coluna in df_bronze.columns:
    print(f'Coluna: {coluna}')
    print(f"Quantidade de valores: {len(df_bronze[coluna])}")
    print(f"Valores únicos: {df_bronze[coluna].nunique()}")
    print(f"Valores nulos: {df_bronze[coluna].isnull().sum()}")
    print(f"Valores duplicados: {df_bronze[coluna].duplicated().sum()}")
    print(f"Tipo dos dados: {df_bronze[coluna].dtypes}")
    print('-------------------------')
    
print("Linhas inteiras duplicadas:", df_bronze.duplicated().sum())

Coluna: customerID
Quantidade de valores: 5634
Valores únicos: 5634
Valores nulos: 0
Valores duplicados: 0
Tipo dos dados: str
-------------------------
Coluna: gender
Quantidade de valores: 5634
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5632
Tipo dos dados: str
-------------------------
Coluna: SeniorCitizen
Quantidade de valores: 5634
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5632
Tipo dos dados: int64
-------------------------
Coluna: Partner
Quantidade de valores: 5634
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5632
Tipo dos dados: str
-------------------------
Coluna: Dependents
Quantidade de valores: 5634
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5632
Tipo dos dados: str
-------------------------
Coluna: tenure
Quantidade de valores: 5634
Valores únicos: 74
Valores nulos: 0
Valores duplicados: 5560
Tipo dos dados: str
-------------------------
Coluna: PhoneService
Quantidade de valores: 5634
Valores únicos: 4
Valores nulos: 0
Valores duplicados: 5630
Tipo dos dados: str
-------------------------
Coluna: MultipleLines
Quantidade de valores: 5634
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: str
-------------------------
Coluna: InternetService
Quantidade de valores: 5634
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: str
-------------------------
Coluna: OnlineSecurity
Quantidade de valores: 5634
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: str
-------------------------
Coluna: OnlineBackup
Quantidade de valores: 5634
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: str
-------------------------
Coluna: DeviceProtection
Quantidade de valores: 5634
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: str
-------------------------
Coluna: TechSupport
Quantidade de valores: 5634
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: str
-------------------------
Coluna: StreamingTV
Quantidade de valores: 5634
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: str
-------------------------
Coluna: StreamingMovies
Quantidade de valores: 5634
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: str
-------------------------
Coluna: Contract
Quantidade de valores: 5634
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: str
-------------------------
Coluna: PaperlessBilling
Quantidade de valores: 5634
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5632
Tipo dos dados: str
-------------------------
Coluna: PaymentMethod
Quantidade de valores: 5634
Valores únicos: 4
Valores nulos: 0
Valores duplicados: 5630
Tipo dos dados: str
-------------------------
Coluna: MonthlyCharges
Quantidade de valores: 5634
Valores únicos: 1490
Valores nulos: 0
Valores duplicados: 4144
Tipo dos dados: float64
-------------------------
Coluna: TotalCharges
Quantidade de valores: 5634
Valores únicos: 5044
Valores nulos: 278
Valores duplicados: 589
Tipo dos dados: float64
-------------------------
Coluna: Churn
Quantidade de valores: 5634
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5632
Tipo dos dados: str
-------------------------
Coluna: CustomerFeedback
Quantidade de valores: 5634
Valores únicos: 5634
Valores nulos: 0
Valores duplicados: 0
Tipo dos dados: str
-------------------------
Coluna: MonthlyIncome
Quantidade de valores: 5634
Valores únicos: 4307
Valores nulos: 0
Valores duplicados: 1327
Tipo dos dados: int64
-------------------------
Linhas inteiras duplicadas: 0

### Remoção de nulos e duplicatas e tratamento para a transformação do tipo da coluna(PhoneService, MultipleLines, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, TotalCharges)

Padronizar ```No```, ```no```, ```Yes```, ```yes```: **PhoneService**

Retirar ```No phone service``` e transformar em No: **MultipleLines**

Retirar ```No internet service``` e transformar em No: **OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies**

Verificar **tenure**: Valores estão como ```unknown```, o que impossibilita transformar em int e realizar calculos

Verificar valores nulos em **TotalCharges**.

In [139]:
df_silver = df_bronze.copy()

In [140]:
# PhoneService
df_silver["PhoneService"] = df_silver["PhoneService"].replace({"no": "No", "yes": "Yes"}) # Transforma os no e yes em No e Yes
df_silver["PhoneService"].unique()

<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

In [141]:
# Tenure
# Calculamos com base no total pago e no valor mensal, assim descobriremos a quatidade de meses
# Se o valor total ou de meses for nulo, excluiremos a linha.

# Converte textos inválidos (como 'unknown') da própria coluna tenure para nulos reais
df_silver["tenure"] = pd.to_numeric(df_silver["tenure"], errors='coerce')

# Calcula os meses (Total / Mensal) e arredonda com o método nativo do Pandas
calculo_tenure = (df_silver["TotalCharges"] / df_silver["MonthlyCharges"]).round()

# Preenche os valores nulos do tenure com o resultado calculado
df_silver["tenure"] = df_silver["tenure"].fillna(calculo_tenure)

# Converte o tenure final para o tipo inteiro otimizado que você escolheu
df_silver["tenure"] = df_silver["tenure"].clip(upper=72).astype("Int16") # Definido limite de meses até 72 e transformação dos dados

# REGRA DE EXCLUSÃO: Se o tenure continuou nulo após o cálculo, remove a linha
df_silver = df_silver.dropna(subset=["tenure"])

Foi removido uma linha pelo fato de que o tenure era nulo e o total pago também, logo não tinha como calcular nem um, nem o outro.

In [142]:
indice_removido = df_bronze.index.difference(df_silver.index)
df_bronze.loc[indice_removido]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,CustomerFeedback,MonthlyIncome
1097,9651-GTSAQ,Female,0,Yes,No,unknown,Yes,No,Fiber optic,Yes,...,Yes,Yes,One year,Yes,Bank transfer (automatic),106.1,NaN,Yes,I have been a customer with this company for o...,4702

In [143]:
print("Bronze:", len(df_bronze), "| Silver:", len(df_silver), "| Removidas:", len(df_bronze) - len(df_silver))

Bronze: 5634 | Silver: 5633 | Removidas: 1

In [144]:
df_silver.shape

(5633, 23)

In [145]:
# TotalCharges
# Transforma os valores nulos em valores aproximados com base no tenure(número de meses) * MonthlyCharges
df_silver["TotalCharges"] = df_silver["TotalCharges"].fillna(df_silver["tenure"] * df_silver["MonthlyCharges"])
df_silver["TotalCharges"].isnull().sum()

np.int64(0)

In [146]:
# Conferindo se há advsersidades
for coluna in df_silver.columns:
    print(f'Coluna: {coluna}')
    print(f"Quantidade de valores: {len(df_silver[coluna])}")
    print(f"Valores únicos: {df_silver[coluna].nunique()}")
    print(f"Valores nulos: {df_silver[coluna].isnull().sum()}")
    print(f"Valores duplicados: {df_silver[coluna].duplicated().sum()}")
    print(f"Tipo dos dados: {df_silver[coluna].dtypes}")
    print('-------------------------')

Coluna: customerID
Quantidade de valores: 5633
Valores únicos: 5633
Valores nulos: 0
Valores duplicados: 0
Tipo dos dados: str
-------------------------
Coluna: gender
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: str
-------------------------
Coluna: SeniorCitizen
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: int64
-------------------------
Coluna: Partner
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: str
-------------------------
Coluna: Dependents
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: str
-------------------------
Coluna: tenure
Quantidade de valores: 5633
Valores únicos: 73
Valores nulos: 0
Valores duplicados: 5560
Tipo dos dados: Int16
-------------------------
Coluna: PhoneService
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: str
-------------------------
Coluna: MultipleLines
Quantidade de valores: 5633
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5630
Tipo dos dados: str
-------------------------
Coluna: InternetService
Quantidade de valores: 5633
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5630
Tipo dos dados: str
-------------------------
Coluna: OnlineSecurity
Quantidade de valores: 5633
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5630
Tipo dos dados: str
-------------------------
Coluna: OnlineBackup
Quantidade de valores: 5633
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5630
Tipo dos dados: str
-------------------------
Coluna: DeviceProtection
Quantidade de valores: 5633
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5630
Tipo dos dados: str
-------------------------
Coluna: TechSupport
Quantidade de valores: 5633
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5630
Tipo dos dados: str
-------------------------
Coluna: StreamingTV
Quantidade de valores: 5633
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5630
Tipo dos dados: str
-------------------------
Coluna: StreamingMovies
Quantidade de valores: 5633
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5630
Tipo dos dados: str
-------------------------
Coluna: Contract
Quantidade de valores: 5633
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5630
Tipo dos dados: str
-------------------------
Coluna: PaperlessBilling
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: str
-------------------------
Coluna: PaymentMethod
Quantidade de valores: 5633
Valores únicos: 4
Valores nulos: 0
Valores duplicados: 5629
Tipo dos dados: str
-------------------------
Coluna: MonthlyCharges
Quantidade de valores: 5633
Valores únicos: 1490
Valores nulos: 0
Valores duplicados: 4143
Tipo dos dados: float64
-------------------------
Coluna: TotalCharges
Quantidade de valores: 5633
Valores únicos: 5286
Valores nulos: 0
Valores duplicados: 347
Tipo dos dados: float64
-------------------------
Coluna: Churn
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: str
-------------------------
Coluna: CustomerFeedback
Quantidade de valores: 5633
Valores únicos: 5633
Valores nulos: 0
Valores duplicados: 0
Tipo dos dados: str
-------------------------
Coluna: MonthlyIncome
Quantidade de valores: 5633
Valores únicos: 4307
Valores nulos: 0
Valores duplicados: 1326
Tipo dos dados: int64
-------------------------

### Tratamento dos dados de cada coluna

In [147]:
# Colunas para string
colunas_sring = ["customerID", "CustomerFeedback"]
for coluna in colunas_sring:
    df_silver[coluna] = df_silver[coluna].astype('string') # Transforma de str para string


# Colunas para categórico
colunas_categorico = ["gender", "InternetService", "Contract", "PaymentMethod", "MultipleLines", "OnlineSecurity", "OnlineBackup", "DeviceProtection", "TechSupport", "StreamingTV", "StreamingMovies",]
for coluna in colunas_categorico:
    df_silver[coluna] = df_silver[coluna].astype('category') # Transforma de str para categorico
    

# Colunas para boolean
colunas_boolean = ["SeniorCitizen", "Partner", "Dependents", "PhoneService", "PaperlessBilling", "Churn"]
mapeamento_booleano = {
    'Yes': True, 'No': False,
    1: True, 0: False,
    '1': True, '0': False
}
for coluna in colunas_boolean:
    df_silver[coluna] = df_silver[coluna].replace(mapeamento_booleano).astype('boolean')


# Para int
df_silver["tenure"] = df_silver["tenure"].astype("Int16")


# Para float
colunas_float = ["MonthlyCharges", "TotalCharges", "MonthlyIncome"]
for coluna in colunas_float:
    df_silver[coluna] = df_silver[coluna].astype('float') # Transforma de str para categorico

### Verificando se os valores foram tratados:

In [148]:
# Conferindo se há advsersidades
for coluna in df_silver.columns:
    print(f'Coluna: {coluna}')
    print(f"Quantidade de valores: {len(df_silver[coluna])}")
    print(f"Valores únicos: {df_silver[coluna].nunique()}")
    print(f"Valores nulos: {df_silver[coluna].isnull().sum()}")
    print(f"Valores duplicados: {df_silver[coluna].duplicated().sum()}")
    print(f"Tipo dos dados: {df_silver[coluna].dtypes}")
    if df_silver[coluna].dtypes == 'boolean' or df_silver[coluna].dtypes == 'category':
        print(10*"-")
        print(f"Valores na coluna: {df_silver[coluna].value_counts().to_string()}")
    print(50*'-')

Coluna: customerID
Quantidade de valores: 5633
Valores únicos: 5633
Valores nulos: 0
Valores duplicados: 0
Tipo dos dados: string
--------------------------------------------------
Coluna: gender
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: category
----------
Valores na coluna: gender
Male      2835
Female    2798
--------------------------------------------------
Coluna: SeniorCitizen
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: boolean
----------
Valores na coluna: SeniorCitizen
False    4705
True      928
--------------------------------------------------
Coluna: Partner
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: boolean
----------
Valores na coluna: Partner
False    2907
True     2726
--------------------------------------------------
Coluna: Dependents
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: boolean
----------
Valores na coluna: Dependents
False    3948
True     1685
--------------------------------------------------
Coluna: tenure
Quantidade de valores: 5633
Valores únicos: 73
Valores nulos: 0
Valores duplicados: 5560
Tipo dos dados: Int16
--------------------------------------------------
Coluna: PhoneService
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: boolean
----------
Valores na coluna: PhoneService
True     5070
False     563
--------------------------------------------------
Coluna: MultipleLines
Quantidade de valores: 5633
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5630
Tipo dos dados: category
----------
Valores na coluna: MultipleLines
No                  2703
Yes                 2367
No phone service     563
--------------------------------------------------
Coluna: InternetService
Quantidade de valores: 5633
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5630
Tipo dos dados: category
----------
Valores na coluna: InternetService
Fiber optic    2476
DSL            1924
No             1233
--------------------------------------------------
Coluna: OnlineSecurity
Quantidade de valores: 5633
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5630
Tipo dos dados: category
----------
Valores na coluna: OnlineSecurity
No                     2803
Yes                    1597
No internet service    1233
--------------------------------------------------
Coluna: OnlineBackup
Quantidade de valores: 5633
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5630
Tipo dos dados: category
----------
Valores na coluna: OnlineBackup
No                     2457
Yes                    1943
No internet service    1233
--------------------------------------------------
Coluna: DeviceProtection
Quantidade de valores: 5633
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5630
Tipo dos dados: category
----------
Valores na coluna: DeviceProtection
No                     2469
Yes                    1931
No internet service    1233
--------------------------------------------------
Coluna: TechSupport
Quantidade de valores: 5633
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5630
Tipo dos dados: category
----------
Valores na coluna: TechSupport
No                     2790
Yes                    1610
No internet service    1233
--------------------------------------------------
Coluna: StreamingTV
Quantidade de valores: 5633
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5630
Tipo dos dados: category
----------
Valores na coluna: StreamingTV
No                     2219
Yes                    2181
No internet service    1233
--------------------------------------------------
Coluna: StreamingMovies
Quantidade de valores: 5633
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5630
Tipo dos dados: category
----------
Valores na coluna: StreamingMovies
No                     2224
Yes                    2176
No internet service    1233
--------------------------------------------------
Coluna: Contract
Quantidade de valores: 5633
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5630
Tipo dos dados: category
----------
Valores na coluna: Contract
Month-to-month    3099
Two year          1347
One year          1187
--------------------------------------------------
Coluna: PaperlessBilling
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: boolean
----------
Valores na coluna: PaperlessBilling
True     3326
False    2307
--------------------------------------------------
Coluna: PaymentMethod
Quantidade de valores: 5633
Valores únicos: 4
Valores nulos: 0
Valores duplicados: 5629
Tipo dos dados: category
----------
Valores na coluna: PaymentMethod
Electronic check             1888
Mailed check                 1283
Credit card (automatic)      1234
Bank transfer (automatic)    1228
--------------------------------------------------
Coluna: MonthlyCharges
Quantidade de valores: 5633
Valores únicos: 1490
Valores nulos: 0
Valores duplicados: 4143
Tipo dos dados: float64
--------------------------------------------------
Coluna: TotalCharges
Quantidade de valores: 5633
Valores únicos: 5286
Valores nulos: 0
Valores duplicados: 347
Tipo dos dados: float64
--------------------------------------------------
Coluna: Churn
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: boolean
----------
Valores na coluna: Churn
False    4130
True     1503
--------------------------------------------------
Coluna: CustomerFeedback
Quantidade de valores: 5633
Valores únicos: 5633
Valores nulos: 0
Valores duplicados: 0
Tipo dos dados: string
--------------------------------------------------
Coluna: MonthlyIncome
Quantidade de valores: 5633
Valores únicos: 4307
Valores nulos: 0
Valores duplicados: 1326
Tipo dos dados: float64
--------------------------------------------------

### Todos os valores dentro do dataframe foram tratados, o que nos leva para a camada gold