In [46]:
# !pip install pandas

In [47]:
import pandas as pd

In [48]:
df_bronze = pd.read_csv('history.csv')

In [49]:
df_bronze.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn',
       'CustomerFeedback', 'MonthlyIncome'],
      dtype='str')

In [50]:
df_bronze.info()

<class 'pandas.DataFrame'>
RangeIndex: 5634 entries, 0 to 5633
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        5634 non-null   str
 1   gender            5634 non-null   str
 2   SeniorCitizen     5634 non-null   int64
 3   Partner           5634 non-null   str
 4   Dependents        5634 non-null   str
 5   tenure            5634 non-null   str
 6   PhoneService      5634 non-null   str
 7   MultipleLines     5634 non-null   str
 8   InternetService   5634 non-null   str
 9   OnlineSecurity    5634 non-null   str
 10  OnlineBackup      5634 non-null   str
 11  DeviceProtection  5634 non-null   str
 12  TechSupport       5634 non-null   str
 13  StreamingTV       5634 non-null   str
 14  StreamingMovies   5634 non-null   str
 15  Contract          5634 non-null   str
 16  PaperlessBilling  5634 non-null   str
 17  PaymentMethod     5634 non-null   str
 18  MonthlyCharges    5634 non-null   float64
 19  TotalCharges      5356 non-null   float64
 20  Churn             5634 non-null   str
 21  CustomerFeedback  5634 non-null   str
 22  MonthlyIncome     5634 non-null   int64
dtypes: float64(2), int64(2), str(19)
memory usage: 4.0 MB

## **Dicionário de dados**

- Varíavel 
- Definição
- Tipagem

| Nº | Coluna             | Descrição                                                                                                              | Tipo de dado         |
| -: | ------------------ | ---------------------------------------------------------------------------------------------------------------------- | -------------------- |
|  0 | `customerID`       | Identificador único do cliente                                                                                         | String               |
|  1 | `gender`           | Gênero do cliente (`Male`, `Female`)                                                                                   | Categórico (2 tipos) |
|  2 | `SeniorCitizen`    | Indica se o cliente é idoso                                                                                            | Boolean              |
|  3 | `Partner`          | Indica se o cliente possui parceiro(a), marido ou esposa                                                               | Boolean              |
|  4 | `Dependents`       | Indica se o cliente possui dependentes, como filhos                                                                    | Boolean              |
|  5 | `tenure`           | Tempo de relacionamento do cliente em meses                                                                            | Int                  |
|  6 | `PhoneService`     | Indica se o cliente possui serviço de telefonia. Padronizar `No`, `no`, `Yes` e `yes`                                  | Boolean              |
|  7 | `MultipleLines`    | Indica se o cliente possui mais de uma linha. Transformar `No phone service` em `No`                                   | Boolean              |
|  8 | `InternetService`  | Tipo de serviço de internet (`DSL`, `No`, `Fiber optic`)                                                               | Categórico (3 tipos) |
|  9 | `OnlineSecurity`   | Indica se o cliente possui serviço de segurança online. Transformar `No internet service` em `No`                      | Boolean              |
| 10 | `OnlineBackup`     | Indica se o cliente possui serviço de backup online. Transformar `No internet service` em `No`                         | Boolean              |
| 11 | `DeviceProtection` | Indica se o cliente possui proteção de dispositivos. Transformar `No internet service` em `No`                         | Boolean              |
| 12 | `TechSupport`      | Indica se o cliente possui suporte técnico. Transformar `No internet service` em `No`                                  | Boolean              |
| 13 | `StreamingTV`      | Indica se o cliente possui serviço de streaming de TV                                                                  | Boolean              |
| 14 | `StreamingMovies`  | Indica se o cliente possui serviço de streaming de filmes                                                              | Boolean              |
| 15 | `Contract`         | Tipo de contrato (`One year`, `Month-to-month`, `Two year`)                                                            | Categórico (3 tipos) |
| 16 | `PaperlessBilling` | Indica se a fatura é digital                                                                                           | Boolean              |
| 17 | `PaymentMethod`    | Método de pagamento (`Electronic check`, `Mailed check`, `Bank transfer (automatic)`, `Credit card (automatic)`)       | Categórico (4 tipos) |
| 18 | `MonthlyCharges`   | Valor cobrado mensalmente pelo plano e pelos serviços contratados                                                      | Float                |
| 19 | `TotalCharges`     | Valor total cobrado durante o período de relacionamento, podendo variar devido a descontos, promoções e outros fatores | Float                |
| 20 | `Churn`            | Indica se o cliente cancelou a assinatura                                                                              | Boolean              |
| 21 | `CustomerFeedback` | Feedback do cliente sobre a assinatura, incluindo pontos positivos e negativos                                         | String               |
| 22 | `MonthlyIncome`    | Renda mensal do cliente                                                                                                | Float                |

In [51]:
df_bronze.shape

(5634, 23)

In [52]:
df_bronze.sample(10)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,CustomerFeedback,MonthlyIncome
4161,6143-JQKEA,Male,0,No,No,10,Yes,No,DSL,No,...,No,No,Month-to-month,Yes,Credit card (automatic),45.80,436.20,No,I have been a customer with this DSL internet ...,9827
1671,7126-RBHSD,Female,0,Yes,No,17,Yes,Yes,Fiber optic,Yes,...,No,No,Month-to-month,No,Electronic check,78.90,1348.95,No,I have been a customer with this company for 1...,163
2192,5501-TVMGM,Male,0,No,No,1,Yes,No,DSL,No,...,No,Yes,Month-to-month,Yes,Electronic check,55.25,55.25,No,I have been using this DSL internet service fo...,6195
1299,9738-QLWTP,Male,0,No,No,39,Yes,No,Fiber optic,No,...,No,No,One year,No,Electronic check,81.90,3219.75,No,I have been a customer with this company for a...,9276
2556,9661-JALZV,Female,0,No,No,58,Yes,Yes,No,No internet service,...,No internet service,No internet service,Two year,Yes,Credit card (automatic),24.70,1519.00,No,I have been a customer with this company for 5...,7762
1224,2928-HLDBA,Female,0,No,No,6,Yes,No,No,No internet service,...,No internet service,No internet service,Month-to-month,No,Mailed check,20.70,112.75,No,I have been a customer with this company for 6...,9014
3607,4993-JCRGJ,Male,0,No,No,26,Yes,Yes,Fiber optic,No,...,No,No,Month-to-month,Yes,Mailed check,84.30,2281.60,No,I have been with this fiber optic internet ser...,9560
4633,6463-MVYRY,Female,1,No,No,57,Yes,No,DSL,Yes,...,Yes,No,Two year,No,Bank transfer (automatic),69.85,4003.00,No,I have been a customer with this company for 5...,5740
1085,8059-UDZFY,Female,1,No,Yes,33,Yes,Yes,Fiber optic,No,...,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),105.35,3465.05,No,I have been a customer of this fiber optic int...,8999
4004,1855-AGAWH,Male,0,Yes,No,31,Yes,No,Fiber optic,No,...,Yes,Yes,One year,Yes,Electronic check,93.80,2939.80,No,I have been a customer with this company for 3...,3785

### Verificação das colunas em geral: quantos valores únicos, nulos e duplicados

In [54]:
for coluna in df_bronze.columns:
    print(f'Coluna: {coluna}')
    print(f"Quantidade de valores: {len(df_bronze[coluna])}")
    print(f"Valores únicos: {df_bronze[coluna].nunique()}")
    print(f"Valores nulos: {df_bronze[coluna].isnull().sum()}")
    print(f"Valores duplicados: {df_bronze[coluna].duplicated().sum()}")
    print(f"Tipo dos dados: {df_bronze[coluna].dtypes}")
    print('-------------------------')
    
print("Linhas inteiras duplicadas:", df_bronze.duplicated().sum())

Coluna: customerID
Quantidade de valores: 5634
Valores únicos: 5634
Valores nulos: 0
Valores duplicados: 0
Tipo dos dados: str
-------------------------
Coluna: gender
Quantidade de valores: 5634
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5632
Tipo dos dados: str
-------------------------
Coluna: SeniorCitizen
Quantidade de valores: 5634
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5632
Tipo dos dados: int64
-------------------------
Coluna: Partner
Quantidade de valores: 5634
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5632
Tipo dos dados: str
-------------------------
Coluna: Dependents
Quantidade de valores: 5634
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5632
Tipo dos dados: str
-------------------------
Coluna: tenure
Quantidade de valores: 5634
Valores únicos: 74
Valores nulos: 0
Valores duplicados: 5560
Tipo dos dados: str
-------------------------
Coluna: PhoneService
Quantidade de valores: 5634
Valores únicos: 4
Valores nulos: 0
Valores duplicados: 5630
Tipo dos dados: str
-------------------------
Coluna: MultipleLines
Quantidade de valores: 5634
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: str
-------------------------
Coluna: InternetService
Quantidade de valores: 5634
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: str
-------------------------
Coluna: OnlineSecurity
Quantidade de valores: 5634
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: str
-------------------------
Coluna: OnlineBackup
Quantidade de valores: 5634
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: str
-------------------------
Coluna: DeviceProtection
Quantidade de valores: 5634
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: str
-------------------------
Coluna: TechSupport
Quantidade de valores: 5634
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: str
-------------------------
Coluna: StreamingTV
Quantidade de valores: 5634
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: str
-------------------------
Coluna: StreamingMovies
Quantidade de valores: 5634
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: str
-------------------------
Coluna: Contract
Quantidade de valores: 5634
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: str
-------------------------
Coluna: PaperlessBilling
Quantidade de valores: 5634
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5632
Tipo dos dados: str
-------------------------
Coluna: PaymentMethod
Quantidade de valores: 5634
Valores únicos: 4
Valores nulos: 0
Valores duplicados: 5630
Tipo dos dados: str
-------------------------
Coluna: MonthlyCharges
Quantidade de valores: 5634
Valores únicos: 1490
Valores nulos: 0
Valores duplicados: 4144
Tipo dos dados: float64
-------------------------
Coluna: TotalCharges
Quantidade de valores: 5634
Valores únicos: 5044
Valores nulos: 278
Valores duplicados: 589
Tipo dos dados: float64
-------------------------
Coluna: Churn
Quantidade de valores: 5634
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5632
Tipo dos dados: str
-------------------------
Coluna: CustomerFeedback
Quantidade de valores: 5634
Valores únicos: 5634
Valores nulos: 0
Valores duplicados: 0
Tipo dos dados: str
-------------------------
Coluna: MonthlyIncome
Quantidade de valores: 5634
Valores únicos: 4307
Valores nulos: 0
Valores duplicados: 1327
Tipo dos dados: int64
-------------------------
Linhas inteiras duplicadas: 0

### Remoção de nulos e duplicatas e tratamento para a transformação do tipo da coluna(PhoneService, MultipleLines, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, TotalCharges)

Padronizar ```No```, ```no```, ```Yes```, ```yes```: **PhoneService**

Retirar ```No phone service``` e transformar em No: **MultipleLines**

Retirar ```No internet service``` e transformar em No: **OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies**

Verificar **tenure**: Valores estão como ```unknown```, o que impossibilita transformar em int e realizar calculos

Verificar valores nulos em **TotalCharges**.

In [ ]:
df_silver = df_bronze.copy()

In [ ]:
# PhoneService
df_silver["PhoneService"] = df_silver["PhoneService"].replace({"no": "No", "yes": "Yes"}) # Transforma os no e yes em No e Yes
df_silver["PhoneService"].unique()

<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

In [ ]:
# MultipleLines
df_silver["MultipleLines"] = df_silver["MultipleLines"].replace({"No phone service": "No"})
df_silver["MultipleLines"].unique()

<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

In [ ]:
# OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies
colunas_tratamento = ['OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies']

for coluna in colunas_tratamento:
    df_silver[coluna] = df_silver[coluna].replace({"No internet service": "No"})
    print(f"Coluna {coluna}:")
    print(df_silver[coluna].unique())
    print(50*"-")

Coluna OnlineSecurity:
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str
--------------------------------------------------
Coluna OnlineBackup:
<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str
--------------------------------------------------
Coluna DeviceProtection:
<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str
--------------------------------------------------
Coluna TechSupport:
<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str
--------------------------------------------------
Coluna StreamingTV:
<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str
--------------------------------------------------
Coluna StreamingMovies:
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str
--------------------------------------------------

In [ ]:
# Tenure
# Calculamos com base no total pago e no valor mensal, assim descobriremos a quatidade de meses
# Se o valor total ou de meses for nulo, excluiremos a linha.

# Converte textos inválidos (como 'unknown') da própria coluna tenure para nulos reais
df_silver["tenure"] = pd.to_numeric(df_silver["tenure"], errors='coerce')

# Calcula os meses (Total / Mensal) e arredonda com o método nativo do Pandas
calculo_tenure = (df_silver["TotalCharges"] / df_silver["MonthlyCharges"]).round()

# Preenche os valores nulos do tenure com o resultado calculado
df_silver["tenure"] = df_silver["tenure"].fillna(calculo_tenure)

# Converte o tenure final para o tipo inteiro otimizado que você escolheu
df_silver["tenure"] = df_silver["tenure"].clip(upper=72).astype("Int16") # Definido limite de meses até 72 e transformação dos dados

# REGRA DE EXCLUSÃO: Se o tenure continuou nulo após o cálculo, remove a linha
df_silver = df_silver.dropna(subset=["tenure"])

Foi removido uma linha pelo fato de que o tenure era nulo e o total pago também, logo não tinha como calcular nem um, nem o outro.

In [57]:
indice_removido = df_bronze.index.difference(df_silver.index)
df_bronze.loc[indice_removido]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,CustomerFeedback,MonthlyIncome
1097,9651-GTSAQ,Female,0,Yes,No,unknown,Yes,No,Fiber optic,Yes,...,Yes,Yes,One year,Yes,Bank transfer (automatic),106.1,NaN,Yes,I have been a customer with this company for o...,4702

In [59]:
print("Bronze:", len(df_bronze), "| Silver:", len(df_silver), "| Removidas:", len(df_bronze) - len(df_silver))

Bronze: 5634 | Silver: 5633 | Removidas: 1

In [ ]:
df_silver.shape

(5633, 23)

In [ ]:
# TotalCharges
# Transforma os valores nulos em valores aproximados com base no tenure(número de meses) * MonthlyCharges
df_silver["TotalCharges"] = df_silver["TotalCharges"].fillna(df_silver["tenure"] * df_silver["MonthlyCharges"])
df_silver["TotalCharges"].isnull().sum()

np.int64(0)

In [ ]:
# Conferindo se há advsersidades
for coluna in df_silver.columns:
    print(f'Coluna: {coluna}')
    print(f"Quantidade de valores: {len(df_silver[coluna])}")
    print(f"Valores únicos: {df_silver[coluna].nunique()}")
    print(f"Valores nulos: {df_silver[coluna].isnull().sum()}")
    print(f"Valores duplicados: {df_silver[coluna].duplicated().sum()}")
    print(f"Tipo dos dados: {df_silver[coluna].dtypes}")
    print('-------------------------')

Coluna: customerID
Quantidade de valores: 5633
Valores únicos: 5633
Valores nulos: 0
Valores duplicados: 0
Tipo dos dados: str
-------------------------
Coluna: gender
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: str
-------------------------
Coluna: SeniorCitizen
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: int64
-------------------------
Coluna: Partner
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: str
-------------------------
Coluna: Dependents
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: str
-------------------------
Coluna: tenure
Quantidade de valores: 5633
Valores únicos: 75
Valores nulos: 0
Valores duplicados: 5558
Tipo dos dados: Int16
-------------------------
Coluna: PhoneService
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: str
-------------------------
Coluna: MultipleLines
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: str
-------------------------
Coluna: InternetService
Quantidade de valores: 5633
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5630
Tipo dos dados: str
-------------------------
Coluna: OnlineSecurity
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: str
-------------------------
Coluna: OnlineBackup
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: str
-------------------------
Coluna: DeviceProtection
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: str
-------------------------
Coluna: TechSupport
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: str
-------------------------
Coluna: StreamingTV
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: str
-------------------------
Coluna: StreamingMovies
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: str
-------------------------
Coluna: Contract
Quantidade de valores: 5633
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5630
Tipo dos dados: str
-------------------------
Coluna: PaperlessBilling
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: str
-------------------------
Coluna: PaymentMethod
Quantidade de valores: 5633
Valores únicos: 4
Valores nulos: 0
Valores duplicados: 5629
Tipo dos dados: str
-------------------------
Coluna: MonthlyCharges
Quantidade de valores: 5633
Valores únicos: 1490
Valores nulos: 0
Valores duplicados: 4143
Tipo dos dados: float64
-------------------------
Coluna: TotalCharges
Quantidade de valores: 5633
Valores únicos: 5286
Valores nulos: 0
Valores duplicados: 347
Tipo dos dados: float64
-------------------------
Coluna: Churn
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: str
-------------------------
Coluna: CustomerFeedback
Quantidade de valores: 5633
Valores únicos: 5633
Valores nulos: 0
Valores duplicados: 0
Tipo dos dados: str
-------------------------
Coluna: MonthlyIncome
Quantidade de valores: 5633
Valores únicos: 4307
Valores nulos: 0
Valores duplicados: 1326
Tipo dos dados: int64
-------------------------

### Tratamento dos dados de cada coluna

In [ ]:
# Colunas para string
colunas_sring = ["customerID", "CustomerFeedback"]
for coluna in colunas_sring:
    df_silver[coluna] = df_silver[coluna].astype('string') # Transforma de str para string


# Colunas para categórico
colunas_categorico = ["gender", "InternetService", "Contract", "PaymentMethod"]
for coluna in colunas_categorico:
    df_silver[coluna] = df_silver[coluna].astype('category') # Transforma de str para categorico
    

# Colunas para boolean
colunas_boolean = ["SeniorCitizen", "Partner", "Dependents", "PhoneService", "MultipleLines", "OnlineSecurity", "OnlineBackup", "DeviceProtection", "TechSupport", "StreamingTV", "StreamingMovies", "PaperlessBilling", "Churn"]
mapeamento_booleano = {
    'Yes': True, 'No': False,
    1: True, 0: False,
    '1': True, '0': False
}
for coluna in colunas_boolean:
    df_silver[coluna] = df_silver[coluna].replace(mapeamento_booleano).astype('boolean')


# Para int
df_silver["tenure"] = df_silver["tenure"].astype("Int16")


# Para float
colunas_float = ["MonthlyCharges", "TotalCharges", "MonthlyIncome"]
for coluna in colunas_float:
    df_silver[coluna] = df_silver[coluna].astype('float') # Transforma de str para categorico

### Verificando se os valores foram tratados:

In [ ]:
# Conferindo se há advsersidades
for coluna in df_silver.columns:
    print(f'Coluna: {coluna}')
    print(f"Quantidade de valores: {len(df_silver[coluna])}")
    print(f"Valores únicos: {df_silver[coluna].nunique()}")
    print(f"Valores nulos: {df_silver[coluna].isnull().sum()}")
    print(f"Valores duplicados: {df_silver[coluna].duplicated().sum()}")
    print(f"Tipo dos dados: {df_silver[coluna].dtypes}")
    print('-------------------------')

Coluna: customerID
Quantidade de valores: 5633
Valores únicos: 5633
Valores nulos: 0
Valores duplicados: 0
Tipo dos dados: string
-------------------------
Coluna: gender
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: category
-------------------------
Coluna: SeniorCitizen
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: boolean
-------------------------
Coluna: Partner
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: boolean
-------------------------
Coluna: Dependents
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: boolean
-------------------------
Coluna: tenure
Quantidade de valores: 5633
Valores únicos: 75
Valores nulos: 0
Valores duplicados: 5558
Tipo dos dados: Int16
-------------------------
Coluna: PhoneService
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: boolean
-------------------------
Coluna: MultipleLines
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: boolean
-------------------------
Coluna: InternetService
Quantidade de valores: 5633
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5630
Tipo dos dados: category
-------------------------
Coluna: OnlineSecurity
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: boolean
-------------------------
Coluna: OnlineBackup
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: boolean
-------------------------
Coluna: DeviceProtection
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: boolean
-------------------------
Coluna: TechSupport
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: boolean
-------------------------
Coluna: StreamingTV
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: boolean
-------------------------
Coluna: StreamingMovies
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: boolean
-------------------------
Coluna: Contract
Quantidade de valores: 5633
Valores únicos: 3
Valores nulos: 0
Valores duplicados: 5630
Tipo dos dados: category
-------------------------
Coluna: PaperlessBilling
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: boolean
-------------------------
Coluna: PaymentMethod
Quantidade de valores: 5633
Valores únicos: 4
Valores nulos: 0
Valores duplicados: 5629
Tipo dos dados: category
-------------------------
Coluna: MonthlyCharges
Quantidade de valores: 5633
Valores únicos: 1490
Valores nulos: 0
Valores duplicados: 4143
Tipo dos dados: float64
-------------------------
Coluna: TotalCharges
Quantidade de valores: 5633
Valores únicos: 5286
Valores nulos: 0
Valores duplicados: 347
Tipo dos dados: float64
-------------------------
Coluna: Churn
Quantidade de valores: 5633
Valores únicos: 2
Valores nulos: 0
Valores duplicados: 5631
Tipo dos dados: boolean
-------------------------
Coluna: CustomerFeedback
Quantidade de valores: 5633
Valores únicos: 5633
Valores nulos: 0
Valores duplicados: 0
Tipo dos dados: string
-------------------------
Coluna: MonthlyIncome
Quantidade de valores: 5633
Valores únicos: 4307
Valores nulos: 0
Valores duplicados: 1326
Tipo dos dados: float64
-------------------------

In [ ]:
for coluna in colunas_boolean:
    print(f"Valores da coluna: {coluna}\n {df_silver[coluna].unique()}")
    print(50*"-")

Valores da coluna: SeniorCitizen
 <BooleanArray>
[False, True]
Length: 2, dtype: boolean
--------------------------------------------------
Valores da coluna: Partner
 <BooleanArray>
[True, False]
Length: 2, dtype: boolean
--------------------------------------------------
Valores da coluna: Dependents
 <BooleanArray>
[True, False]
Length: 2, dtype: boolean
--------------------------------------------------
Valores da coluna: PhoneService
 <BooleanArray>
[True, False]
Length: 2, dtype: boolean
--------------------------------------------------
Valores da coluna: MultipleLines
 <BooleanArray>
[False, True]
Length: 2, dtype: boolean
--------------------------------------------------
Valores da coluna: OnlineSecurity
 <BooleanArray>
[False, True]
Length: 2, dtype: boolean
--------------------------------------------------
Valores da coluna: OnlineBackup
 <BooleanArray>
[True, False]
Length: 2, dtype: boolean
--------------------------------------------------
Valores da coluna: DeviceProtection
 <BooleanArray>
[True, False]
Length: 2, dtype: boolean
--------------------------------------------------
Valores da coluna: TechSupport
 <BooleanArray>
[True, False]
Length: 2, dtype: boolean
--------------------------------------------------
Valores da coluna: StreamingTV
 <BooleanArray>
[True, False]
Length: 2, dtype: boolean
--------------------------------------------------
Valores da coluna: StreamingMovies
 <BooleanArray>
[False, True]
Length: 2, dtype: boolean
--------------------------------------------------
Valores da coluna: PaperlessBilling
 <BooleanArray>
[True, False]
Length: 2, dtype: boolean
--------------------------------------------------
Valores da coluna: Churn
 <BooleanArray>
[False, True]
Length: 2, dtype: boolean
--------------------------------------------------

### Todos os valores dentro do dataframe foram tratados, o que nos leva para a camada gold